#!/bin/bash

# Fix monitor layout
xrandr --output DP-4 --mode 2560x1080 --rate 60.00 --output DP-2 --mode 1920x1080 --rate 60.00 --right-of DP-4 --output DP-0 --mode 1920x1080 --rate 60.00 --left-of DP-4 &

